train_vae:
  model_params:
    name: 'VanillaVAE'
    in_channels: 3
    latent_dim: 128

  exp_params:
    dataset: celeba
    data_path: "datasets/"
    img_size: 64
    batch_size: 64 # Better to have a square number
    LR: 0.005
    weight_decay: 0.0
    scheduler_gamma: 0.95

  trainer_params:
    gpus: 1
    max_nb_epochs: 25
    max_epochs: 25

  logging_params:
    save_dir: "args.tl_outdir"
    name: "VanillaVAE"
    manual_seed: 1265

test_vae:
  base:
    - train_vae
  ckpt_path: "results/PyTorch_VAE/train_vae_\
    20200904-22_12_37_179/ckptdir/_ckpt_epoch_3.ckpt"


