train_vae:
  model_params:
    name: 'VanillaVAE'
    in_channels: 3
    latent_dim: 128
    img_size: 64

  exp_params:
    dataset: celeba
    data_path: "datasets/"
    img_size: 64
    batch_size: 64 # Better to have a square number
    LR: 0.005
    weight_decay: 0.0
    scheduler_gamma: 0.95

  trainer_params:
    gpus: 1
    max_nb_epochs: 40
    max_epochs: 40

  logging_params:
    save_dir: "args.tl_outdir"
    name: "VanillaVAE"
    manual_seed: 1265

test_vae:
  base:
    - train_vae
  ckpt_path: "results/PyTorch_VAE/train_vae_20200917/ckptdir/_ckpt_epoch_99.ckpt"
  update_cfg: true
  GAN_metric:
    name: "TFFIDISScore"
    tf_fid_stat: "data/tf_fid_stats_cifar10_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
    num_inception_images: 50000


